In [9]:
## IoU

In [10]:
import torch
import torchvision.ops as ops

# Define bounding boxes
boxes1 = torch.tensor([
    [10, 10, 20, 20],
    [15, 15, 25, 25]
], dtype=torch.float32)

boxes2 = torch.tensor([
    [12, 12, 22, 22],
    [30, 30, 40, 40]
], dtype=torch.float32)

# Compute IoU
iou_matrix = ops.box_iou(boxes1, boxes2)

print(iou_matrix)


tensor([[0.4706, 0.0000],
        [0.3245, 0.0000]])


In [19]:
## Non MaX SUPRESSION

In [17]:
import torch
import torchvision.ops as ops

# Define bounding boxes and scores
boxes = torch.tensor([
    [50, 50, 200, 200],
    [55, 55, 210, 210],
    [200, 200, 300, 300],
    [220, 220, 310, 310]
], dtype=torch.float32)

scores = torch.tensor([0.9, 0.75, 0.85, 0.8], dtype=torch.float32)

# Set IoU threshold
iou_threshold = 0.5

# Perform NMS
keep = ops.nms(boxes, scores, iou_threshold)

# Filter the bounding boxes and scores
kept_boxes = boxes[keep]
kept_scores = scores[keep]

print("Kept boxes:")
print(kept_boxes)
print("Kept scores:")
print(kept_scores)


Kept boxes:
tensor([[ 50.,  50., 200., 200.],
        [200., 200., 300., 300.]])
Kept scores:
tensor([0.9000, 0.8500])


In [1]:
import torch
import torchmetrics

# Define ground truth and predictions
gt_boxes = torch.tensor([
    [50, 50, 200, 200],
    [30, 30, 100, 100]
], dtype=torch.float32)

gt_labels = torch.tensor([0, 1], dtype=torch.int64)

pred_boxes = torch.tensor([
    [48, 48, 198, 198],
    [70, 70, 130, 130],
    [250, 250, 300, 300]
], dtype=torch.float32)

pred_scores = torch.tensor([0.9, 0.75, 0.6], dtype=torch.float32)
pred_labels = torch.tensor([0, 1, 2], dtype=torch.int64)

# Initialize the metric
metric = torchmetrics.detection.MeanAveragePrecision()

# Update the metric with predictions and ground truth
metric.update(pred_boxes, pred_scores, pred_labels, gt_boxes, gt_labels)

# Compute the mean average precision
mAP = metric.compute()
print("Mean Average Precision (mAP):", mAP)


TypeError: MeanAveragePrecision.update() takes 3 positional arguments but 6 were given